config.skyMap["discrete"].projection = "TAN"
config.skyMap["discrete"].raList = [320.36749197602893]
config.skyMap["discrete"].decList = [0.3131554006070023]
config.skyMap["discrete"].radiusList = [1.4388796242707318]
config.skyMap["discrete"].rotation = 0.0
config.skyMap["discrete"].patchBorder = 100
config.skyMap["discrete"].tractOverlap = 0.0
config.skyMap["discrete"].pixelScale = 0.168
config.skyMap["discrete"].patchInnerDimensions = [4000, 4000]
config.skyMap["discrete"].tractBuilder["cells"].cellBorder = 0
config.skyMap["discrete"].tractBuilder["cells"].cellInnerDimensions=[100, 100]
config.skyMap["discrete"].tractBuilder["cells"].numCellsInPatchBorder = 1
config.skyMap["discrete"].tractBuilder["cells"].numCellsPerPatchInner=40
config.skyMap["discrete"].tractBuilder = "cells"
config.skyMap.name = "discrete"
config.name = 'discrete/ci_hsc'
